apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betstream-chart.fullname" . }}-secrets
  labels:
    {{- include "betstream-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: {{ .Values.secrets.connectionString | quote }}
  jwtKey: {{ .Values.secrets.jwtKey | quote }}
