FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["BetStream/BetStream.csproj", "BetStream/"]
COPY ["BetStream.Application/BetStream.Application.csproj", "BetStream.Application/"]
COPY ["BetStream.Domain/BetStream.Domain.csproj", "BetStream.Domain/"]

RUN dotnet restore "./BetStream/BetStream.csproj"

COPY . .
WORKDIR "/src/BetStream"

RUN dotnet build "./BetStream.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./BetStream.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "BetStream.dll"]